function mainCtrl($scope) {
    let megidoList = [
        {
            no:1,
            name:"アイム",
            image_url:"images/megido/アイム.png"
        },
        {
            no:2,
            name:"アイム(R)",
            image_url:"images/megido/アイム(R).png"
        },
        {
            no:3,
            name:"アガリアレプト",
            image_url:"images/megido/アガリアレプト.png"
        },
        {
            no:4,
            name:"アガリアレプト(R)",
            image_url:"images/megido/アガリアレプト(R).png"
        },
        {
            no:5,
            name:"アガレス",
            image_url:"images/megido/アガレス.png"
        },
        {
            no:6,
            name:"アガレス(C)",
            image_url:"images/megido/アガレス(C).png"
        },
        {
            no:7,
            name:"アクィエル",
            image_url:"images/megido/アクィエル.png"
        },
        {
            no:8,
            name:"アザゼル",
            image_url:"images/megido/アザゼル.png"
        },
        {
            no:9,
            name:"アスタロト",
            image_url:"images/megido/アスタロト.png"
        },
        {
            no:10,
            name:"アスタロト(B)",
            image_url:"images/megido/アスタロト(B).png"
        },
        {
            no:11,
            name:"アスモデウス",
            image_url:"images/megido/アスモデウス.png"
        },
        {
            no:12,
            name:"アスラフィル",
            image_url:"images/megido/アスラフィル.png"
        },
        {
            no:13,
            name:"アバラム",
            image_url:"images/megido/アバラム.png"
        },
        {
            no:14,
            name:"アマイモン",
            image_url:"images/megido/アマイモン.png"
        },
        {
            no:15,
            name:"アマイモン(R)",
            image_url:"images/megido/アマイモン(R).png"
        },
        {
            no:16,
            name:"アマゼロト",
            image_url:"images/megido/アマゼロト.png"
        },
        {
            no:17,
            name:"アミー",
            image_url:"images/megido/アミー.png"
        },
        {
            no:18,
            name:"アムドゥスキアス",
            image_url:"images/megido/アムドゥスキアス.png"
        },
        {
            no:19,
            name:"アモン",
            image_url:"images/megido/アモン.png"
        },
        {
            no:20,
            name:"アモン(R)",
            image_url:"images/megido/アモン(R).png"
        },
        {
            no:21,
            name:"アラストール",
            image_url:"images/megido/アラストール.png"
        },
        {
            no:22,
            name:"アラストール(B)",
            image_url:"images/megido/アラストール(B).png"
        },
        {
            no:23,
            name:"アリトン",
            image_url:"images/megido/アリトン.png"
        },
        {
            no:24,
            name:"アロケル",
            image_url:"images/megido/アロケル.png"
        },
        {
            no:25,
            name:"アンドラス",
            image_url:"images/megido/アンドラス.png"
        },
        {
            no:26,
            name:"アンドラス(C)",
            image_url:"images/megido/アンドラス(C).png"
        },
        {
            no:27,
            name:"アンドレアルフス",
            image_url:"images/megido/アンドレアルフス.png"
        },
        {
            no:28,
            name:"アンドロマリウス",
            image_url:"images/megido/アンドロマリウス.png"
        },
        {
            no:29,
            name:"イポス",
            image_url:"images/megido/イポス.png"
        },
        {
            no:30,
            name:"イポス(C)",
            image_url:"images/megido/イポス(C).png"
        },
        {
            no:31,
            name:"インキュバス",
            image_url:"images/megido/インキュバス.png"
        },
        {
            no:32,
            name:"インキュバス(C)",
            image_url:"images/megido/インキュバス(C).png"
        },
        {
            no:33,
            name:"インプ",
            image_url:"images/megido/インプ.png"
        },
        {
            no:34,
            name:"ウァサゴ",
            image_url:"images/megido/ウァサゴ.png"
        },
        {
            no:35,
            name:"ウァプラ",
            image_url:"images/megido/ウァプラ.png"
        },
        {
            no:36,
            name:"ウァプラ(R)",
            image_url:"images/megido/ウァプラ(R).png"
        },
        {
            no:37,
            name:"ウァラク",
            image_url:"images/megido/ウァラク.png"
        },
        {
            no:38,
            name:"ウァレフォル",
            image_url:"images/megido/ウァレフォル.png"
        },
        {
            no:39,
            name:"ヴィネ",
            image_url:"images/megido/ヴィネ.png"
        },
        {
            no:40,
            name:"ヴィネ(R)",
            image_url:"images/megido/ヴィネ(R).png"
        },
        {
            no:41,
            name:"ウヴァル",
            image_url:"images/megido/ウヴァル.png"
        },
        {
            no:42,
            name:"ウェパル",
            image_url:"images/megido/ウェパル.png"
        },
        {
            no:43,
            name:"ウェパル(B)",
            image_url:"images/megido/ウェパル(B).png"
        },
        {
            no:44,
            name:"ヴェルドレ",
            image_url:"images/megido/ヴェルドレ.png"
        },
        {
            no:45,
            name:"ウトゥック",
            image_url:"images/megido/ウトゥック.png"
        },
        {
            no:46,
            name:"エリゴス",
            image_url:"images/megido/エリゴス.png"
        },
        {
            no:47,
            name:"エリゴス(B)",
            image_url:"images/megido/エリゴス(B).png"
        },
        {
            no:48,
            name:"オセ",
            image_url:"images/megido/オセ.png"
        },
        {
            no:49,
            name:"オリアス",
            image_url:"images/megido/オリアス.png"
        },
        {
            no:50,
            name:"オリアス(C)",
            image_url:"images/megido/オリアス(C).png"
        },
        {
            no:51,
            name:"オリエンス",
            image_url:"images/megido/オリエンス.png"
        },
        {
            no:52,
            name:"オレイ",
            image_url:"images/megido/オレイ.png"
        },
        {
            no:53,
            name:"オロバス",
            image_url:"images/megido/オロバス.png"
        },
        {
            no:54,
            name:"オロバス(C)",
            image_url:"images/megido/オロバス(C).png"
        },
        {
            no:55,
            name:"ガープ",
            image_url:"images/megido/ガープ.png"
        },
        {
            no:56,
            name:"カイム",
            image_url:"images/megido/カイム.png"
        },
        {
            no:57,
            name:"カスピエル",
            image_url:"images/megido/カスピエル.png"
        },
        {
            no:58,
            name:"カスピエル(C)",
            image_url:"images/megido/カスピエル(C).png"
        },
        {
            no:59,
            name:"ガミジン",
            image_url:"images/megido/ガミジン.png"
        },
        {
            no:60,
            name:"キマリス",
            image_url:"images/megido/キマリス.png"
        },
        {
            no:61,
            name:"キマリス(C)",
            image_url:"images/megido/キマリス(C).png"
        },
        {
            no:62,
            name:"グザファン",
            image_url:"images/megido/グザファン.png"
        },
        {
            no:63,
            name:"グシオン",
            image_url:"images/megido/グシオン.png"
        },
        {
            no:64,
            name:"グシオン(B)",
            image_url:"images/megido/グシオン(B).png"
        },
        {
            no:65,
            name:"グラシャラボラス",
            image_url:"images/megido/グラシャラボラス.png"
        },
        {
            no:66,
            name:"グラシャラボラス(C)",
            image_url:"images/megido/グラシャラボラス(C).png"
        },
        {
            no:67,
            name:"グリマルキン",
            image_url:"images/megido/グリマルキン.png"
        },
        {
            no:68,
            name:"グレモリー",
            image_url:"images/megido/グレモリー.png"
        },
        {
            no:69,
            name:"クロケル",
            image_url:"images/megido/クロケル.png"
        },
        {
            no:70,
            name:"クロケル(R)",
            image_url:"images/megido/クロケル(R).png"
        },
        {
            no:71,
            name:"コルソン",
            image_url:"images/megido/コルソン.png"
        },
        {
            no:72,
            name:"コルソン(R)",
            image_url:"images/megido/コルソン(R).png"
        },
        {
            no:73,
            name:"ザガン",
            image_url:"images/megido/ザガン.png"
        },
        {
            no:74,
            name:"サキュバス",
            image_url:"images/megido/サキュバス.png"
        },
        {
            no:75,
            name:"サキュバス(B)",
            image_url:"images/megido/サキュバス(B).png"
        },
        {
            no:76,
            name:"サタナイル",
            image_url:"images/megido/サタナイル.png"
        },
        {
            no:77,
            name:"サタナキア",
            image_url:"images/megido/サタナキア.png"
        },
        {
            no:78,
            name:"サタナキア(B)",
            image_url:"images/megido/サタナキア(B).png"
        },
        {
            no:79,
            name:"サブナック",
            image_url:"images/megido/サブナック.png"
        },
        {
            no:80,
            name:"サラ",
            image_url:"images/megido/サラ.png"
        },
        {
            no:81,
            name:"サルガタナス",
            image_url:"images/megido/サルガタナス.png"
        },
        {
            no:82,
            name:"サレオス",
            image_url:"images/megido/サレオス.png"
        },
        {
            no:83,
            name:"サレオス(C)",
            image_url:"images/megido/サレオス(C).png"
        },
        {
            no:84,
            name:"ジズ",
            image_url:"images/megido/ジズ.png"
        },
        {
            no:85,
            name:"ジズ(R)",
            image_url:"images/megido/ジズ(R).png"
        },
        {
            no:86,
            name:"シトリー",
            image_url:"images/megido/シトリー.png"
        },
        {
            no:87,
            name:"シトリー(R)",
            image_url:"images/megido/シトリー(R).png"
        },
        {
            no:88,
            name:"ジニマル",
            image_url:"images/megido/ジニマル.png"
        },
        {
            no:89,
            name:"シャックス",
            image_url:"images/megido/シャックス.png"
        },
        {
            no:90,
            name:"シャックス(B)",
            image_url:"images/megido/シャックス(B).png"
        },
        {
            no:91,
            name:"シャミハザ",
            image_url:"images/megido/シャミハザ.png"
        },
        {
            no:92,
            name:"シャミハザ(R)",
            image_url:"images/megido/シャミハザ(R).png"
        },
        {
            no:93,
            name:"スコルベノト",
            image_url:"images/megido/スコルベノト.png"
        },
        {
            no:94,
            name:"ストラス",
            image_url:"images/megido/ストラス.png"
        },
        {
            no:95,
            name:"ストラス(R)",
            image_url:"images/megido/ストラス(R).png"
        },
        {
            no:96,
            name:"セーレ",
            image_url:"images/megido/セーレ.png"
        },
        {
            no:97,
            name:"セーレ(R)",
            image_url:"images/megido/セーレ(R).png"
        },
        {
            no:98,
            name:"ゼパル",
            image_url:"images/megido/ゼパル.png"
        },
        {
            no:99,
            name:"ゼパル(C)",
            image_url:"images/megido/ゼパル(C).png"
        },
        {
            no:100,
            name:"ダゴン",
            image_url:"images/megido/ダゴン.png"
        },
        {
            no:101,
            name:"タナトス",
            image_url:"images/megido/タナトス.png"
        },
        {
            no:102,
            name:"タムス",
            image_url:"images/megido/タムス.png"
        },
        {
            no:103,
            name:"ダンタリオン",
            image_url:"images/megido/ダンタリオン.png"
        },
        {
            no:104,
            name:"ダンタリオン(R)",
            image_url:"images/megido/ダンタリオン(R).png"
        },
        {
            no:105,
            name:"ティアマト",
            image_url:"images/megido/ティアマト.png"
        },
        {
            no:106,
            name:"デカラビア",
            image_url:"images/megido/デカラビア.png"
        },
        {
            no:107,
            name:"デカラビア(B)",
            image_url:"images/megido/デカラビア(B).png"
        },
        {
            no:108,
            name:"ナベリウス",
            image_url:"images/megido/ナベリウス.png"
        },
        {
            no:109,
            name:"ニスロク",
            image_url:"images/megido/ニスロク.png"
        },
        {
            no:110,
            name:"ニバス",
            image_url:"images/megido/ニバス.png"
        },
        {
            no:111,
            name:"ニバス(B)",
            image_url:"images/megido/ニバス(B).png"
        },
        {
            no:112,
            name:"ネフィリム",
            image_url:"images/megido/ネフィリム.png"
        },
        {
            no:113,
            name:"ネルガル",
            image_url:"images/megido/ネルガル.png"
        },
        {
            no:114,
            name:"ハーゲンティ",
            image_url:"images/megido/ハーゲンティ.png"
        },
        {
            no:115,
            name:"ハーゲンティ(B)",
            image_url:"images/megido/ハーゲンティ(B).png"
        },
        {
            no:116,
            name:"バールゼフォン",
            image_url:"images/megido/バールゼフォン.png"
        },
        {
            no:117,
            name:"バールゼフォン(C)",
            image_url:"images/megido/バールゼフォン(C).png"
        },
        {
            no:118,
            name:"パイモン",
            image_url:"images/megido/パイモン.png"
        },
        {
            no:119,
            name:"バエル",
            image_url:"images/megido/バエル.png"
        },
        {
            no:120,
            name:"ハック",
            image_url:"images/megido/ハック.png"
        },
        {
            no:121,
            name:"バティン",
            image_url:"images/megido/バティン.png"
        },
        {
            no:122,
            name:"バティン(B)",
            image_url:"images/megido/バティン(B).png"
        },
        {
            no:123,
            name:"バフォメット",
            image_url:"images/megido/バフォメット.png"
        },
        {
            no:124,
            name:"ロノウェ",
            image_url:"images/megido/ロノウェ.png"
        },
        {
            no:125,
            name:"バラキエル",
            image_url:"images/megido/バラキエル.png"
        },
        {
            no:126,
            name:"バラム",
            image_url:"images/megido/バラム.png"
        },
        {
            no:127,
            name:"バルバトス",
            image_url:"images/megido/バルバトス.png"
        },
        {
            no:128,
            name:"バルバトス(R)",
            image_url:"images/megido/バルバトス(R).png"
        },
        {
            no:129,
            name:"ハルファス",
            image_url:"images/megido/ハルファス.png"
        },
        {
            no:130,
            name:"ビフロンス",
            image_url:"images/megido/ビフロンス.png"
        },
        {
            no:131,
            name:"ビフロンス(C)",
            image_url:"images/megido/ビフロンス(C).png"
        },
        {
            no:132,
            name:"ヒュトギン",
            image_url:"images/megido/ヒュトギン.png"
        },
        {
            no:133,
            name:"フィロタヌス",
            image_url:"images/megido/フィロタヌス.png"
        },
        {
            no:134,
            name:"フェニックス",
            image_url:"images/megido/フェニックス.png"
        },
        {
            no:135,
            name:"フェニックス(C)",
            image_url:"images/megido/フェニックス(C).png"
        },
        {
            no:136,
            name:"ブエル",
            image_url:"images/megido/ブエル.png"
        },
        {
            no:137,
            name:"フォカロル",
            image_url:"images/megido/フォカロル.png"
        },
        {
            no:138,
            name:"フォカロル(R)",
            image_url:"images/megido/フォカロル(R).png"
        },
        {
            no:139,
            name:"フォラス",
            image_url:"images/megido/フォラス.png"
        },
        {
            no:140,
            name:"フォルネウス",
            image_url:"images/megido/フォルネウス.png"
        },
        {
            no:141,
            name:"ブニ",
            image_url:"images/megido/ブニ.png"
        },
        {
            no:142,
            name:"ブニ(B)",
            image_url:"images/megido/ブニ(B).png"
        },
        {
            no:143,
            name:"ブネ",
            image_url:"images/megido/ブネ.png"
        },
        {
            no:144,
            name:"ブネ(B)",
            image_url:"images/megido/ブネ(B).png"
        },
        {
            no:145,
            name:"フラウロス",
            image_url:"images/megido/フラウロス.png"
        },
        {
            no:146,
            name:"フラウロス(B)",
            image_url:"images/megido/フラウロス(B).png"
        },
        {
            no:147,
            name:"フリアエ",
            image_url:"images/megido/フリアエ.png"
        },
        {
            no:148,
            name:"フルーレティ",
            image_url:"images/megido/フルーレティ.png"
        },
        {
            no:149,
            name:"フルカス",
            image_url:"images/megido/フルカス.png"
        },
        {
            no:150,
            name:"フルカス(C)",
            image_url:"images/megido/フルカス(C).png"
        },
        {
            no:151,
            name:"プルソン",
            image_url:"images/megido/プルソン.png"
        },
        {
            no:152,
            name:"プルフラス",
            image_url:"images/megido/プルフラス.png"
        },
        {
            no:153,
            name:"プルフラス(B)",
            image_url:"images/megido/プルフラス(B).png"
        },
        {
            no:154,
            name:"フルフル",
            image_url:"images/megido/フルフル.png"
        },
        {
            no:155,
            name:"フルフル(C)",
            image_url:"images/megido/フルフル(C).png"
        },
        {
            no:156,
            name:"プロメテウス",
            image_url:"images/megido/プロメテウス.png"
        },
        {
            no:157,
            name:"ベバル",
            image_url:"images/megido/ベバル.png"
        },
        {
            no:158,
            name:"ベヒモス",
            image_url:"images/megido/ベヒモス.png"
        },
        {
            no:159,
            name:"ベヒモス(B)",
            image_url:"images/megido/ベヒモス(B).png"
        },
        {
            no:160,
            name:"ベリアル",
            image_url:"images/megido/ベリアル.png"
        },
        {
            no:161,
            name:"ベリアル(B)",
            image_url:"images/megido/ベリアル(B).png"
        },
        {
            no:162,
            name:"ベリト",
            image_url:"images/megido/ベリト.png"
        },
        {
            no:163,
            name:"ベリト(B)",
            image_url:"images/megido/ベリト(B).png"
        },
        {
            no:164,
            name:"ベルフェゴール",
            image_url:"images/megido/ベルフェゴール.png"
        },
        {
            no:165,
            name:"レラジェ",
            image_url:"images/megido/レラジェ.png"
        },
        {
            no:166,
            name:"レラジェ(R)",
            image_url:"images/megido/レラジェ(R).png"
        },
        {
            no:167,
            name:"ベレト",
            image_url:"images/megido/ベレト.png"
        },
        {
            no:168,
            name:"ボディス",
            image_url:"images/megido/ボディス.png"
        },
        {
            no:169,
            name:"マスティマ",
            image_url:"images/megido/マスティマ.png"
        },
        {
            no:170,
            name:"マモン",
            image_url:"images/megido/マモン.png"
        },
        {
            no:171,
            name:"マルコシアス",
            image_url:"images/megido/マルコシアス.png"
        },
        {
            no:172,
            name:"マルコシアス(B)",
            image_url:"images/megido/マルコシアス(B).png"
        },
        {
            no:173,
            name:"マルチネ",
            image_url:"images/megido/マルチネ.png"
        },
        {
            no:174,
            name:"マルバス(R)",
            image_url:"images/megido/マルバス(R).png"
        },
        {
            no:175,
            name:"マルバス",
            image_url:"images/megido/マルバス.png"
        },
        {
            no:176,
            name:"マルファス",
            image_url:"images/megido/マルファス.png"
        },
        {
            no:177,
            name:"ミノソン",
            image_url:"images/megido/ミノソン.png"
        },
        {
            no:178,
            name:"ムルムル",
            image_url:"images/megido/ムルムル.png"
        },
        {
            no:179,
            name:"メフィスト",
            image_url:"images/megido/メフィスト.png"
        },
        {
            no:180,
            name:"メフィスト(C)",
            image_url:"images/megido/メフィスト(C).png"
        },
        {
            no:181,
            name:"モラクス",
            image_url:"images/megido/モラクス.png"
        },
        {
            no:182,
            name:"ユフィール",
            image_url:"images/megido/ユフィール.png"
        },
        {
            no:183,
            name:"ユフィール(C)",
            image_url:"images/megido/ユフィール(C).png"
        },
        {
            no:184,
            name:"ラウム",
            image_url:"images/megido/ラウム.png"
        },
        {
            no:185,
            name:"ラウム(C)",
            image_url:"images/megido/ラウム(C).png"
        },
        {
            no:186,
            name:"リヴァイアサン",
            image_url:"images/megido/リヴァイアサン.png"
        },
        {
            no:187,
            name:"リリム",
            image_url:"images/megido/リリム.png"
        },
        {
            no:188,
            name:"リリム(R)",
            image_url:"images/megido/リリム(R).png"
        },
        {
            no:189,
            name:"ルキフゲス",
            image_url:"images/megido/ルキフゲス.png"
        }        
    ];

    $scope.megidoList = megidoList;
    $scope.searchName = "";

    $scope.search = function() {
        searchResults = [];
        searchName = document.getElementById("search").value;
        console.log(searchName);

        for(let i =0; i < megidoList.length; i++){
            console.log("roop:"+megidoList[i].name);
            if(searchName === megidoList[i].name){
                console.log("検索に引っ掛かりました");
                searchResults.push(megidoList[i]);
                $scope.megidoList = searchResults;
                searchName = ''
                break;
            }
        }
    };
}